"""Insight generation: executive summaries, recommendations, risks, follow-ups.

The BI assistant must never make claims the data cannot support. Every summary
line here is derived from the actual query result, the dataset schema
(``columns_info``) or both. Recommendations always reference real columns, and
follow-up questions are generated by ``ai.questions`` so they can never suggest
columns the dataset does not have (e.g. a time trend without a date column).
"""
from .columns import _parse_columns_info
from .profile import detect_currency, format_number, _money
from .questions import (
    classify_columns,
    _preferred_metric,
    _preferred_category,
    generate_follow_ups,
    _singularize,
    _pluralize,
    extract_entity,
)
from .semantics import format_semantic_value

_ANALYSIS_KEYWORDS = [
    "analyze", "analysis", "summary", "overview", "describe", "tell me about",
    "business review", "report", "dashboard",
    "insights", "key insights", "key metrics", "key stats", "key figures", "key numbers",
]


def _fmt(value) -> str:
    """Format a possibly non-numeric value as a number, falling back to its text.

    PostgreSQL aggregate columns can surface as Decimal (serialized to float) or,
    for user-typed text columns, as strings; never crash on the format spec.
    """
    try:
        return f"{float(value):,.2f}"
    except (TypeError, ValueError):
        return str(value)


def _fmt_col(value, col: str, semantic_types: dict, currency) -> str:
    """Format a value according to the column's detected semantic type so e.g.
    COUNT results are plain integers and only monetary columns get currency."""
    st = (semantic_types or {}).get(col)
    if not st:
        from .semantics import infer_semantic_type

        st = infer_semantic_type(col)
    if st == "currency":
        return format_semantic_value(value, "currency", currency)
    return format_semantic_value(value, st, currency)


_LABEL_PREFIXES = [
    ("total_", "Total "),
    ("sum_", "Total "),
    ("avg_", "Average "),
    ("min_", "Minimum "),
    ("max_", "Maximum "),
]


def _metric_label(col: str) -> str:
    low = col.lower()
    for prefix, label in _LABEL_PREFIXES:
        if low.startswith(prefix):
            return label + col[len(prefix):].replace("_", " ")
    return col.replace("_", " ")


def _pseudo_columns(columns: list, data_sample: list) -> list:
    """Build lightweight metadata when no ``columns_info`` is available so the
    schema-aware follow-up generator still has something grounded to work with."""
    pseudo = []
    for col in columns:
        vals = [r.get(col) for r in data_sample if isinstance(r.get(col), (int, float))]
        low = col.lower()
        ctype = "metric" if vals else (
            "date" if any(k in low for k in ("date", "time", "day", "month", "year", "quarter", "week"))
            else "categorical"
        )
        pseudo.append({"name": col, "type": ctype, "dtype": "float64" if ctype == "metric" else "object"})
    return pseudo


def _data_columns(data_sample: list, columns: list) -> dict:
    numeric, text = [], []
    num_rows = len(data_sample)
    for col in columns:
        vals = [row.get(col) for row in data_sample if isinstance(row.get(col), (int, float))]
        if vals and len(vals) > num_rows * 0.5:
            numeric.append(col)
        else:
            text.append(col)
    date = [c for c in columns if any(k in c.lower() for k in ("date", "time", "day", "month", "year", "quarter", "week"))]
    return {"numeric": numeric, "text": text, "date": date}


def generate_insights(question: str, data_sample: list, columns: list, columns_info: str = "",
                      enrichment: dict = None, dataset_name: str = "", semantic_types: dict = None) -> dict:
    num_rows = len(data_sample)
    num_cols = len(columns)

    summaries: list = []
    recommendations: list = []
    risks: list = []
    follow_ups: list = []

    cols_meta = _parse_columns_info(columns_info) if columns_info else _pseudo_columns(columns, data_sample)
    groups = classify_columns(cols_meta)
    metric = _preferred_metric(groups["numeric"])
    dimension = _preferred_category(groups["categorical"])
    has_date = bool(groups["date"])

    currency = (enrichment or {}).get("currency") or (
        detect_currency(dataset_name, groups["numeric"] + groups["categorical"]) if dataset_name else None
    )

    q = question.lower()
    is_analysis = any(kw in q for kw in _ANALYSIS_KEYWORDS)

    # ── Single-value KPI result ───────────────────────────────────────────
    if num_rows == 1 and num_cols == 1:
        col = columns[0]
        val = data_sample[0].get(col)
        if isinstance(val, (int, float)):
            low = col.lower()
            is_count = "count" in low
            is_avg = any(k in low for k in ("avg", "average", "mean"))
            is_sum = any(k in low for k in ("sum", "total"))
            label = (enrichment or {}).get("metric") or _metric_label(col)
            by_dim = (enrichment or {}).get("by_dimension") or []
            total = (enrichment or {}).get("total")
            row_count = (enrichment or {}).get("row_count")
            dim = (enrichment or {}).get("dimension")

            if is_count:
                summaries.append(f"There are {int(val):,} records in the dataset.")
            elif enrichment and (enrichment.get("metric") or by_dim):
                if is_avg:
                    summaries.append(f"Average {label} is {_money(label, val, currency)} per record.")
                else:
                    across = f" across {row_count:,} records" if row_count else ""
                    summaries.append(f"Total {label} is {_money(label, val, currency)}{across}.")
                if by_dim and total and total > 0 and dim:
                    top_name, top_val = by_dim[0]
                    pct = top_val / total * 100
                    summaries.append(f"The leading {dim} is '{top_name}' with {_money(label, top_val, currency)} ({pct:.1f}% of total {label}).")
            elif is_sum:
                summaries.append(f"Total {label} is {_money(label, val, currency)}.")
            elif is_avg:
                summaries.append(f"Average {label} is {_money(label, val, currency)}.")
            else:
                summaries.append(f"The {label} value is {format_number(val, currency)}.")

            # Schema-grounded recommendations
            if dimension and metric:
                recommendations.append(f"Compare {metric} across {dimension} to see where the largest share comes from.")
            if dimension:
                recommendations.append(f"Drill into individual records by {dimension} to find the drivers behind this figure.")
            if has_date:
                recommendations.append(f"Track {label} over time to spot trends and seasonality.")

            # Risks
            if row_count is not None and row_count < 50:
                risks.append(f"Small dataset ({row_count:,} records) — insights may not be statistically significant.")
            risks.append("This is a single aggregated value; segment-level variation may be hidden.")
            risks.append("Results are based on the queried subset — broader trends may differ.")

            follow_ups = generate_follow_ups(question, cols_meta)
            return {
                "executive_summary": summaries[:5],
                "recommendations": recommendations[:3],
                "risks": risks[:2],
                "follow_up_questions": follow_ups[:5],
            }

    # ── Comprehensive analysis / business summary ─────────────────────────
    if is_analysis and num_rows == 1:
        row = data_sample[0]
        kpi_parts = []
        for col in columns:
            low = col.lower()
            val = row.get(col)
            if val is None:
                continue
            if "total_records" in low or low in ("count", "total_count"):
                kpi_parts.append(f"Total records: {int(val):,}")
            elif "unique" in low or "distinct" in low:
                dim_name = col.replace("unique_", "").replace("_", " ")
                kpi_parts.append(f"Unique {dim_name}: {int(val):,}")
            elif low.startswith("avg_"):
                kpi_parts.append(f"Average {col[4:].replace('_', ' ')}: {_fmt(val)}")
            elif low.startswith("min_"):
                kpi_parts.append(f"Min {col[4:].replace('_', ' ')}: {_fmt(val)}")
            elif low.startswith("max_"):
                kpi_parts.append(f"Max {col[4:].replace('_', ' ')}: {_fmt(val)}")
            elif low.startswith("total_"):
                kpi_parts.append(f"Total {col[6:].replace('_', ' ')}: {_fmt(val)}")
            elif isinstance(val, (int, float)):
                kpi_parts.append(f"{col.replace('_', ' ')}: {_fmt(val)}")
            else:
                kpi_parts.append(f"{col}: {val}")

        summaries.extend(kpi_parts)

        # Grounded dataset narrative
        total_records = next((int(row.get(c)) for c in columns if "total_records" in c.lower()), num_rows)
        if total_records:
            summaries.append(f"This dataset contains {total_records:,} records across {num_cols} column(s).")

        if has_date:
            summaries.append(f"Time-based trends can be analyzed using '{groups['date'][0]}'.")
        else:
            risks.append("This dataset has no date/time column, so time-based trend analysis is not possible.")

        # Recommendations - always grounded in real columns
        if metric:
            recommendations.append(f"Rank records by {metric} to spot outliers and best performers.")
        if dimension:
            recommendations.append(f"Compare {metric or 'metrics'} across {dimension} to identify the strongest segment.")
        if has_date and metric:
            recommendations.append(f"Track {metric} over time to identify seasonality and growth patterns.")
        if not recommendations:
            recommendations.append("Explore the individual columns to uncover patterns not visible in aggregate statistics.")

        # Risks - grounded
        if total_records and total_records < 50:
            risks.append(f"Small dataset ({total_records:,} records) — insights may not be statistically significant.")
        if num_cols and total_records:
            risks.append("Aggregate statistics can mask important segment-level variations.")
        risks.append("Results are based on the queried subset — broader trends may differ.")

        follow_ups = generate_follow_ups(question, cols_meta)
        return {
            "executive_summary": summaries[:8],
            "recommendations": recommendations[:3],
            "risks": risks[:3],
            "follow_up_questions": follow_ups[:5],
        }

    # ── Single-row multi-column result (incl. percentage shares) ──────────
    if num_rows == 1 and num_cols >= 2:
        row = data_sample[0]
        pct_cols = [c for c in columns if any(k in c.lower() for k in ("percentage", "pct", "share", "proportion"))]
        dim_val = next((row.get(c) for c in columns if isinstance(row.get(c), str)), None)
        met_col = next((c for c in columns if isinstance(row.get(c), (int, float))), None)

        if pct_cols and dim_val is not None and met_col is not None:
            pct_val = row.get(pct_cols[0])
            total_col = next((c for c in columns if "total" in c.lower() and c != pct_cols[0]), None)
            label = _metric_label(total_col).replace("Total ", "").strip() if total_col else _metric_label(met_col)
            summaries.append(f"'{dim_val}' accounts for {_fmt(pct_val)}% of total {label}.")
            if total_col:
                summaries.append(f"Total {label} is {_fmt_col(row.get(total_col), total_col, semantic_types, currency)}.")
            if dimension and metric:
                recommendations.append(f"Compare {dimension} shares of {metric} to prioritize where to focus.")
                recommendations.append(f"Explore what drives {dim_val}'s share of {metric}.")
        elif dim_val is not None and met_col is not None:
            label = _metric_label(met_col)
            summaries.append(f"The {dimension or columns[0]} '{dim_val}' has {label} of {_fmt_col(row.get(met_col), met_col, semantic_types, currency)}.")

        for col in columns:
            val = row.get(col)
            if val is None:
                continue
            if isinstance(val, (int, float)):
                if any(k in col.lower() for k in ("percentage", "pct", "share", "proportion")):
                    summaries.append(f"{_metric_label(col)}: {_fmt(val)}%")
                else:
                    summaries.append(f"{_metric_label(col)}: {_fmt_col(val, col, semantic_types, currency)}")
            else:
                summaries.append(f"{col.replace('_', ' ')}: {val}")

        if dimension and metric:
            recommendations.append(f"Rank all {dimension} groups by {metric} for a fuller comparison.")
        if has_date:
            recommendations.append(f"Track {metric or 'this metric'} over time to see how this figure changes.")
        if num_rows < 5:
            risks.append("This is a single-row result — segment-level variation may be hidden.")
        risks.append("Results are based on the queried subset — broader trends may differ.")

        follow_ups = generate_follow_ups(question, cols_meta)
        return {
            "executive_summary": summaries[:6],
            "recommendations": recommendations[:3],
            "risks": risks[:2],
            "follow_up_questions": follow_ups[:5],
        }

    # ── Comparison insights (e.g., "profit comparison across regions") ────
    dc = _data_columns(data_sample, columns)
    is_comparison = any(w in q for w in ["comparison", "compare", "across"])
    if is_comparison and dc["text"] and dc["numeric"]:
        dim_col = dc["text"][0]
        met_col = dc["numeric"][0]
        values = [(row.get(dim_col, "Unknown"), row.get(met_col, 0) or 0) for row in data_sample]
        values.sort(key=lambda x: x[1], reverse=True)

        if values:
            top_name, top_val = values[0]
            summaries.append(f"'{top_name}' leads with {_fmt_col(top_val, met_col, semantic_types, currency)} in {_metric_label(met_col)}.")
        if len(values) >= 2:
            second_name, second_val = values[1]
            summaries.append(f"'{second_name}' follows with {_fmt_col(second_val, met_col, semantic_types, currency)}.")
        if len(values) >= 2:
            bottom_name, bottom_val = values[-1]
            summaries.append(f"'{bottom_name}' has the lowest at {_fmt_col(bottom_val, met_col, semantic_types, currency)}.")
        if len(values) >= 2:
            total = sum(v for _, v in values)
            top_pct = (top_val / total * 100) if total > 0 else 0
            summaries.append(f"'{top_name}' accounts for {top_pct:.0f}% of total {_metric_label(met_col)}.")

        avg_val = sum(v for _, v in values) / len(values) if values else 0
        summaries.append(f"The average {_metric_label(met_col)} across all {dim_col}s is {_fmt_col(avg_val, met_col, semantic_types, currency)}.")

        if len(values) >= 2:
            recommendations.append(f"Drill into '{top_name}' to identify what drives its high {_metric_label(met_col)}.")
            recommendations.append(f"Analyze why '{values[-1][0]}' underperforms and explore improvement opportunities.")
        if has_date:
            recommendations.append(f"Compare {_metric_label(met_col)} trends over time for top and bottom {dim_col}s.")

        follow_ups = generate_follow_ups(question, cols_meta)
        return {
            "executive_summary": summaries[:5],
            "recommendations": recommendations[:3],
            "risks": risks[:2],
            "follow_up_questions": follow_ups[:5],
        }

    # ── Ranking insights (e.g., "top 5 products by revenue") ──────────────
    is_ranking = any(w in q for w in ["top ", "top 5", "top 10", "bottom ", "rank", "best", "worst", "highest", "lowest", "most", "least"])
    if is_ranking and dc["numeric"]:
        met_col = dc["numeric"][0]
        values = [row.get(met_col, 0) or 0 for row in data_sample]
        if values:
            max_val = max(values)
            min_val = min(values)
            avg_val = sum(values) / len(values)
            st = (semantic_types or {}).get(met_col)
            if not st:
                from .semantics import infer_semantic_type

                st = infer_semantic_type(met_col)
            is_count = st == "count"

            dim_label = (dc["text"][0] if dc["text"] else "group").replace("_", " ").lower()
            entity = extract_entity(question)
            if is_count:
                if entity:
                    label = f"{_singularize(entity)} count"
                    ent_sing = _singularize(entity)
                    ent_plural = _pluralize(ent_sing)
                else:
                    label = _metric_label(met_col)
                    ent_sing, ent_plural = "", ""
            else:
                label = _metric_label(met_col)
                ent_sing, ent_plural = "", ""

            max_str = f"{int(round(max_val)):,}" if is_count else format_number(max_val, currency)
            min_str = f"{int(round(min_val)):,}" if is_count else format_number(min_val, currency)

            # All groups tied -> describe the tie, never a meaningless range.
            if max_val == min_val and num_rows > 1 and dc["text"]:
                names = [str(row.get(dc["text"][0], "Unknown")) for row in data_sample]
                if is_count and ent_sing:
                    summaries.append(f"All {num_rows} {_pluralize(dim_label)} have {int(round(max_val)):,} {ent_sing} each.")
                else:
                    summaries.append(f"All {num_rows} {_pluralize(dim_label)} have the same {label} of {max_str}.")
                if len(names) > 1:
                    head, last = ", ".join(names[:-1]), names[-1]
                    summaries.append(f"{head}, and {last} are tied for the highest {label}.")
            elif num_rows <= 20:
                if is_count:
                    summaries.append(f"{label} ranges from {min_str} to {max_str} (average: {int(round(avg_val)):,}).")
                else:
                    summaries.append(f"{label} ranges from {min_str} to {max_str} (average: {format_number(avg_val, currency)}).")
            else:
                summaries.append(f"Showing top {num_rows} records by {label}.")

            if max_val > min_val and dc["text"]:
                top_row = max(data_sample, key=lambda r: r.get(met_col, 0) or 0)
                top_name = top_row.get(dc["text"][0], "Unknown")
                summaries.append(f"'{top_name}' tops the list with {max_str}.")
                if num_rows > 1:
                    bottom_row = min(data_sample, key=lambda r: r.get(met_col, 0) or 0)
                    bottom_name = bottom_row.get(dc["text"][0], "Unknown")
                    summaries.append(f"'{bottom_name}' ranks last with {min_str}.")

        if dc["text"]:
            if len(values) > 1 and max_val == min_val:
                dim_word = _pluralize(dc["text"][0].replace("_", " ")).lower()
                total_count = int(round(sum(values)))
                if ent_plural:
                    recommendations.append(
                        f"All {num_rows} {dim_word} have equal {ent_plural} representation. "
                        f"Because the dataset contains only {total_count} {ent_plural}, there is "
                        f"insufficient evidence of concentration in any single {dc['text'][0].replace('_', ' ').lower()}."
                    )
                else:
                    recommendations.append(
                        f"All {num_rows} {dim_word} have equal {label}. "
                        f"With only {total_count} records across {num_rows} {dim_word}, there is "
                        f"insufficient evidence of concentration."
                    )
            else:
                recommendations.append(f"Explore what differentiates top-performing {dc['text'][0].replace('_', ' ')}s from the rest.")
        if max_val > min_val:
            recommendations.append(f"Consider which drivers of {label} can be optimized for better results.")

        follow_ups = generate_follow_ups(question, cols_meta)
        return {
            "executive_summary": summaries[:5],
            "recommendations": recommendations[:3],
            "risks": risks[:2],
            "follow_up_questions": follow_ups[:5],
        }

    # ── Default: data-driven insights ─────────────────────────────────────
    summaries.append(f"Query returned {num_rows} row{'s' if num_rows != 1 else ''} across {num_cols} column{'s' if num_cols != 1 else ''}.")

    for col in dc["numeric"]:
        values = [row.get(col) for row in data_sample if isinstance(row.get(col), (int, float))]
        if not values or len(values) < 2:
            continue
        total = sum(values)
        avg_val = total / len(values)
        max_val = max(values)
        min_val = min(values)
        summaries.append(f"'{_metric_label(col)}' ranges from {_fmt_col(min_val, col, semantic_types, currency)} to {_fmt_col(max_val, col, semantic_types, currency)} (average: {_fmt_col(avg_val, col, semantic_types, currency)}).")

        if num_rows > 1:
            sorted_vals = sorted(values, reverse=True)
            if sorted_vals[0] != sorted_vals[-1] and total > 0:
                top_pct = sorted_vals[0] / total * 100
                if top_pct > 50:
                    summaries.append(f"Top entry accounts for {top_pct:.0f}% of total '{_metric_label(col)}'.")
        break

    for col in dc["text"]:
        val_counts = {}
        for row in data_sample:
            v = row.get(col)
            if v is not None:
                val_counts[str(v)] = val_counts.get(str(v), 0) + 1
        if val_counts:
            top_val = max(val_counts, key=val_counts.get)
            top_count = val_counts[top_val]
            unique_count = len(val_counts)
            if unique_count > 1:
                summaries.append(f"Top '{col}' is '{top_val}' ({top_count} occurrences) among {unique_count} unique values.")
            else:
                summaries.append(f"'{col}' has a single value: '{top_val}'.")
        break

    if not summaries:
        summaries.append("The data contains structured records suitable for analysis.")

    if dc["numeric"] and dc["text"]:
        recommendations.append(f"Analyze '{_metric_label(dc['numeric'][0])}' by '{dc['text'][0]}' to identify patterns.")
    if has_date and metric:
        recommendations.append(f"Track {metric} over time to identify trends.")
    if dc["text"]:
        recommendations.append(f"Explore the distribution of records by '{dc['text'][0]}'.")

    if num_rows < 5:
        risks.append(f"Small sample size ({num_rows} rows) may not be representative.")
    if num_rows > 0:
        risks.append("Results are based on the queried subset — broader trends may differ.")

    follow_ups = generate_follow_ups(question, cols_meta)
    return {
        "executive_summary": summaries[:5],
        "recommendations": recommendations[:3],
        "risks": risks[:2],
        "follow_up_questions": follow_ups[:5],
    }
