import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import {
  Sparkles, ArrowRight, BarChart3, Brain, Shield, Zap,
  Database, MessageSquare, TrendingUp, Globe, ChevronRight,
  Star, CheckCircle2, Play
} from 'lucide-react';
import { HeroScene, MiniDataViz } from '../components/Scene3D';

const fadeUp = {
  hidden: { opacity: 0, y: 30 },
  visible: (i = 0) => ({
    opacity: 1,
    y: 0,
    transition: { delay: i * 0.1, duration: 0.6, ease: 'easeOut' },
  }),
};

const Landing = () => {
  const [activeFeature, setActiveFeature] = useState(0);

  const features = [
    {
      icon: MessageSquare,
      title: 'Natural Language Queries',
      desc: 'Ask questions about your data in plain English. Our AI translates your questions into precise SQL queries instantly.',
      color: 'from-primary-500 to-primary-700',
      glow: 'shadow-primary-500/20',
      viz: 'sphere',
    },
    {
      icon: BarChart3,
      title: 'Smart Visualizations',
      desc: 'Automatic chart generation — bar, line, pie, and table views. The AI picks the best visualization for your data.',
      color: 'from-amber-500 to-amber-700',
      glow: 'shadow-amber-500/20',
      viz: 'wire',
    },
    {
      icon: Brain,
      title: 'AI-Powered Insights',
      desc: 'Get executive summaries, recommendations, risk analysis, and follow-up questions generated by advanced AI.',
      color: 'from-primary-600 to-red-800',
      glow: 'shadow-primary-500/20',
      viz: 'brain',
    },
    {
      icon: Shield,
      title: 'Enterprise Security',
      desc: 'JWT authentication, role-based access, SQL injection prevention, and encrypted data storage keep your data safe.',
      color: 'from-dark-600 to-dark-800',
      glow: 'shadow-dark-500/10',
      viz: 'ring',
    },
  ];

  const stats = [
    { value: '10x', label: 'Faster Insights', icon: Zap },
    { value: '99.9%', label: 'Query Accuracy', icon: CheckCircle2 },
    { value: '50+', label: 'Chart Types', icon: BarChart3 },
    { value: '24/7', label: 'AI Available', icon: Globe },
  ];

  const steps = [
    { num: '01', title: 'Upload Your Data', desc: 'Drag and drop CSV, Excel, or PDF files. Our cleaner auto-detects columns and types.' },
    { num: '02', title: 'Ask in English', desc: 'Type a question like "Show me top 10 customers by revenue". No SQL knowledge needed.' },
    { num: '03', title: 'Get Visual Insights', desc: 'Receive beautiful charts, executive summaries, and actionable recommendations instantly.' },
  ];

  return (
    <div className="min-h-screen bg-dark-950 relative overflow-hidden">
      {/* ═══════ HERO SECTION ═══════ */}
      <section className="relative min-h-screen flex items-center justify-center px-4">
        {/* 3D Background */}
        <div className="absolute inset-0 z-0">
          <HeroScene />
        </div>

        {/* Gradient overlays */}
        <div className="absolute inset-0 bg-gradient-to-b from-dark-950/40 via-transparent to-dark-950 z-[1]" />
        <div className="absolute bottom-0 left-0 right-0 h-40 bg-gradient-to-t from-dark-950 to-transparent z-[1]" />

        {/* Hero Content */}
        <div className="relative z-10 text-center max-w-5xl mx-auto pt-20">
          <motion.div
            initial="hidden"
            animate="visible"
            variants={fadeUp}
            custom={0}
            className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary-500/10 border border-primary-500/20 text-primary-400 text-sm font-medium mb-8"
          >
            <Sparkles className="w-4 h-4" />
            Powered by Generative AI
            <ArrowRight className="w-3 h-3" />
          </motion.div>

          <motion.h1
            initial="hidden"
            animate="visible"
            variants={fadeUp}
            custom={1}
            className="text-clamp-title font-black tracking-tight mb-6"
          >
            <span className="text-white">Ask Your Data</span>
            <br />
            <span className="gradient-text text-glow">Anything</span>
          </motion.h1>

          <motion.p
            initial="hidden"
            animate="visible"
            variants={fadeUp}
            custom={2}
            className="text-clamp-body text-dark-300 max-w-2xl mx-auto mb-10 leading-relaxed"
          >
            Transform raw data into actionable intelligence using natural language.
            No SQL expertise required — just ask questions and get beautiful visualizations.
          </motion.p>

          <motion.div
            initial="hidden"
            animate="visible"
            variants={fadeUp}
            custom={3}
            className="flex flex-col sm:flex-row gap-4 justify-center items-center"
          >
            <Link
              to="/register"
              id="hero-cta-register"
              className="group btn-primary text-lg px-8 py-4 flex items-center gap-3 animate-pulse-ring"
            >
              Get Started Free
              <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
            </Link>
            <Link
              to="/login"
              id="hero-cta-login"
              className="btn-secondary text-lg px-8 py-4 flex items-center gap-3"
            >
              <Play className="w-5 h-5" />
              Watch Demo
            </Link>
          </motion.div>

          {/* Trust indicators */}
          <motion.div
            initial="hidden"
            animate="visible"
            variants={fadeUp}
            custom={4}
            className="flex items-center justify-center gap-6 mt-12 text-dark-500 text-sm"
          >
            <span className="flex items-center gap-1"><CheckCircle2 className="w-4 h-4 text-emerald-500" /> Free to start</span>
            <span className="flex items-center gap-1"><Shield className="w-4 h-4 text-primary-500" /> Enterprise-grade security</span>
            <span className="flex items-center gap-1"><Zap className="w-4 h-4 text-amber-500" /> Instant setup</span>
          </motion.div>
        </div>
      </section>

      {/* ═══════ STATS BAR ═══════ */}
      <section className="relative z-10 py-16 border-y border-dark-800">
        <div className="max-w-6xl mx-auto px-4">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {stats.map((stat, i) => (
              <motion.div
                key={stat.label}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="text-center group"
              >
                <div className="w-12 h-12 mx-auto mb-3 rounded-xl bg-primary-500/10 flex items-center justify-center group-hover:bg-primary-500/20 transition-colors">
                  <stat.icon className="w-6 h-6 text-primary-400" />
                </div>
                <p className="text-3xl md:text-4xl font-bold gradient-text mb-1">{stat.value}</p>
                <p className="text-dark-400 text-sm">{stat.label}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ═══════ FEATURES ═══════ */}
      <section className="relative z-10 py-24 px-4">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <span className="text-primary-400 text-sm font-semibold uppercase tracking-wider">Features</span>
            <h2 className="text-clamp-h1 font-bold text-white mt-3 mb-4">
              Everything You Need for
              <span className="gradient-text"> Data Intelligence</span>
            </h2>
            <p className="text-dark-400 text-lg max-w-2xl mx-auto">
              A complete platform that turns your raw data into powerful insights with zero technical knowledge required.
            </p>
          </motion.div>

          <div className="grid lg:grid-cols-2 gap-8">
            {/* Feature list */}
            <div className="space-y-4">
              {features.map((f, i) => (
                <motion.div
                  key={f.title}
                  initial={{ opacity: 0, x: -20 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.1 }}
                  onClick={() => setActiveFeature(i)}
                  className={`p-6 rounded-2xl cursor-pointer transition-all duration-300 border ${
                    activeFeature === i
                      ? 'bg-dark-800/80 border-primary-500/30 shadow-lg shadow-primary-500/10'
                      : 'bg-dark-800/30 border-dark-700/30 hover:border-dark-600'
                  }`}
                >
                  <div className="flex items-start gap-4">
                    <div className={`w-12 h-12 rounded-xl bg-gradient-to-br ${f.color} flex items-center justify-center flex-shrink-0 ${f.glow} shadow-lg`}>
                      <f.icon className="w-6 h-6 text-white" />
                    </div>
                    <div>
                      <h3 className="text-lg font-semibold text-white mb-1">{f.title}</h3>
                      <p className="text-dark-400 text-sm leading-relaxed">{f.desc}</p>
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>

            {/* 3D Preview */}
            <motion.div
              initial={{ opacity: 0, scale: 0.9 }}
              whileInView={{ opacity: 1, scale: 1 }}
              viewport={{ once: true }}
              className="relative rounded-2xl bg-dark-800/30 border border-dark-700/50 overflow-hidden min-h-[400px] flex items-center justify-center"
            >
              <div className="absolute inset-0">
                <MiniDataViz type={features[activeFeature].viz} />
              </div>
              <div className="absolute bottom-6 left-6 right-6 p-4 glass-card">
                <p className="text-sm text-dark-300 font-medium flex items-center gap-2">
                  <Star className="w-4 h-4 text-amber-400" />
                  {features[activeFeature].title}
                </p>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* ═══════ HOW IT WORKS ═══════ */}
      <section className="relative z-10 py-24 px-4 bg-dark-900/50">
        <div className="max-w-5xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <span className="text-primary-500 text-sm font-bold uppercase tracking-wider">How It Works</span>
            <h2 className="text-clamp-h1 font-bold text-white mt-3 mb-4">
              Three Steps to <span className="gradient-text">Brilliance</span>
            </h2>
          </motion.div>

          <div className="grid md:grid-cols-3 gap-8">
            {steps.map((step, i) => (
              <motion.div
                key={step.num}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.15 }}
                className="relative glass-card-hover p-8 group"
              >
                <span className="text-6xl font-black text-dark-700 group-hover:text-primary-900/10 transition-colors absolute top-4 right-4">
                  {step.num}
                </span>
                <div className="relative z-10">
                  <div className="w-12 h-12 rounded-xl bg-primary-500 flex items-center justify-center mb-4 shadow-lg shadow-primary-500/25">
                    <span className="text-white font-bold text-lg">{parseInt(step.num)}</span>
                  </div>
                  <h3 className="text-xl font-bold text-white mb-2">{step.title}</h3>
                  <p className="text-dark-400 leading-relaxed">{step.desc}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ═══════ CTA ═══════ */}
      <section className="relative z-10 py-24 px-4">
        <div className="max-w-4xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            className="glass-card p-12 md:p-16 relative overflow-hidden"
          >
            <div className="absolute inset-0 bg-gradient-to-br from-primary-600/10 via-transparent to-primary-700/5" />
            <div className="relative z-10">
              <h2 className="text-3xl md:text-5xl font-bold text-white mb-4">
                Ready to Transform Your
                <span className="gradient-text"> Data?</span>
              </h2>
              <p className="text-dark-300 text-lg mb-8 max-w-xl mx-auto">
                Join thousands of analysts who've replaced complex SQL with simple conversations.
              </p>
              <Link
                to="/register"
                id="cta-register"
                className="btn-primary text-lg px-10 py-4 inline-flex items-center gap-3"
              >
                Start for Free
                <ChevronRight className="w-5 h-5" />
              </Link>
            </div>
          </motion.div>
        </div>
      </section>

      {/* ═══════ FOOTER ═══════ */}
      <footer className="relative z-10 py-12 px-4 border-t border-dark-800">
        <div className="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-dark-900 border border-primary-500/30 flex items-center justify-center">
              <Sparkles className="w-4 h-4 text-primary-500" />
            </div>
            <span className="font-black text-white uppercase tracking-tighter select-none">GenAI<span className="text-primary-500">BI</span></span>
          </div>
          <p className="text-dark-500 text-sm">
            © 2026 GenAI BI Platform. Powered by Generative AI.
          </p>
          <div className="flex gap-6 text-dark-400 text-sm">
            <span className="hover:text-primary-400 cursor-pointer transition-colors">Privacy</span>
            <span className="hover:text-primary-400 cursor-pointer transition-colors">Terms</span>
            <span className="hover:text-primary-400 cursor-pointer transition-colors">Support</span>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Landing;
